manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: devcharmander
      url-base: https://github.com/devcharmander
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: corne-peripheral-animation
      remote: devcharmander
      revision: main
  self:
    path: config
